- DirectXTex/DirectXTexWIC.cpp
I noticed that if srgb is not set for the texture formet, the PNG writer will still put an sRGB/RenderingIntent into the PNG header, and will not have a correct gamma value of 1.0. I added code that works for my application.
> Added support for linear color space PNG writing

- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/Filters.h
Hello,
I'm trying to compile DirectXTex with Clang 5 (inside Visual Studio 2017) but I'm getting errors:
In file included from DirectXTex\DirectXTex_Z.cpp:15:
DirectXTex/DirectXTexConvert.cpp(3851,9): error : use of overloaded operator '-' is ambiguous (operand type 'const DirectX::XMVECTORF32')
I propose this fix, but maybe a better thing to do is to fix FXMVECTOR operators ?
> Fix compiler errors (Clang 5.0.0)

- DDSView/ddsview.cpp
This allows to correctly sample from sRGB textures and write back
correct colors to backbuffer. Also work with linear RGB textures.
> DDSView: Set the render target view to sRGB format

- .editorconfig
- DirectXTex_Desktop_2017.sln
- DirectXTex_Desktop_2017_Win10.sln
- DirectXTex_Windows10.sln
- DirectXTex_XboxOneXDK_2017.sln
Add editor configs to VS2017 solutions.
Mostly ensures that tab formatting stays consistent regardless of IDE global settings.
> Add VS2017 editor configs

- DirectXTex/DirectXTexConvert.cpp
WIC when converting FP32 values that are out of range to FP16 will end up producing NaNs, which are pretty much never good for textures. The non-WIC paths clamp values to the Min/Max range instead.
The fix was to just add another case to the ``UseWICConversion`` test function that tries to steer clear of scenarios where WIC "does the wrong thing"
> Force non-WIC paths for FP32->FP16 conversions

- DirectXTex/DirectXTexImage.cpp
the threshold was changed from { 0.99f, 0.99f, 0.99f, 0.99f } to { 0.997f, 0.997f, 0.997f, 0.997f }
to handle a case when opacity of pixel defined with color (254,254,254)
in this case alpha = { 0.996078491f, 0.996078491f, 0.996078491f, 0.996078491f }  
All others color values from 0 to 253 works fine with threshold=0.99f, only "254" has exception.
> DirectTexImage::IsAlphaAllOpaque() changed threshold to handle a case when opacity of pixel defined with color (254,254,254)

- DirectXTex/BC.cpp
- DirectXTex/BC.h
- DirectXTex/BC4BC5.cpp
- DirectXTex/BC6HBC7.cpp
- DirectXTex/BCDirectCompute.cpp
- DirectXTex/DDS.h
- DirectXTex/DirectXTexCompress.cpp
- DirectXTex/DirectXTexCompressGPU.cpp
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexD3D11.cpp
- DirectXTex/DirectXTexD3D12.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexFlipRotate.cpp
- DirectXTex/DirectXTexHDR.cpp
- DirectXTex/DirectXTexImage.cpp
- DirectXTex/DirectXTexMipmaps.cpp
- DirectXTex/DirectXTexMisc.cpp
- DirectXTex/DirectXTexNormalMaps.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexPMAlpha.cpp
- DirectXTex/DirectXTexResize.cpp
- DirectXTex/DirectXTexTGA.cpp
- DirectXTex/DirectXTexUtil.cpp
- DirectXTex/DirectXTexWIC.cpp
- DirectXTex/Filters.h
Fix for ``InitOnceExecuteOnce`` failing to build with clang x86.
Also various code review cleanup based on clang warnings.
> Fix compiler errors (Clang 6)

- DirectXTex/BC6HBC7.cpp
Fix OOB memory read.
To reproduce, download this file:
https://github.com/knarkowicz/GPURealTimeBC6H/blob/master/bin/yucca.dds
Then run:
texconv.exe -nogpu -f BC6H_SF16 -m 1 -y yucca.dds
At some points, fDot will be -1.2, causing iStep to underflow, causing a crash.
> Fix out-of-bounds read

- DDSTextureLoader/DDSTextureLoader.cpp
- DDSTextureLoader/DDSTextureLoader12.cpp
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexHDR.cpp
- DirectXTex/DirectXTexImage.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexTGA.cpp
- DirectXTex/DirectXTexUtil.cpp
- ScreenGrab/ScreenGrab.cpp
- ScreenGrab/ScreenGrab12.cpp
On 32-bit builds, ``ComputePitch`` could overflow a 32-bit integer for overall image size and it wouldn't have resulted in failures until later. This primarily happens with 16k textures that use ``DXGI_FORMAT_R32G32B32A32_FLOAT`` as most other formats fit in the 32-bit limits.
This pull request modifies ``ComputePitch`` to return an ``HRESULT``. The primary result is now  ``S_OK``, ``HRESULT_FROM_WIN32(ERROR_ARITHMETIC_OVERFLOW)``, or in the rare case of an invalid DXIG format ``E_INVALID``.
I also added more guards where ``size_t`` values are cast to 32-bit integers.
> ComputePitch now returns an HRESULT

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexWIC.cpp
There was already a ``WIC_FLAGS_IGNORE_SRGB`` to ignore sRGB metadata on the reader, but wasn't any way to force the writing of sRGB metadata on the writer when the input format is *not* 8:8:8:8 which has a ``DXGI_*_SRGB`` equivalent format (i.e. there is no ``_SRGB`` equivalent of say ``DXGI_FORMAT_R10G10B10A2_UNORM``).
This adds ``WIC_FLAGS_FORCE_SRGB`` which forces the writing of the sRGB metadata chunk instead of the gAMA 1.0 chunk. ``WIC_FLAGS_FORCE_LINEAR`` does the opposite.
> This flag only applies to PNG, JPEG, and TIFF WIC container formats.
> Added WIC_FLAGS_FORCE_SRGB / LINEAR flags for WIC writer

- DirectXTex_Desktop_2019.sln
- DirectXTex_Desktop_2019_Win10.sln
Without this change the Visual Studio Version Selector will try to open these solutions with Visual Studio 2017 and fail to find the v142 toolchain. Version number used is from the 16.0.0 release and used in new solutions created with that version of the IDE. No additional changes were required for individual project files.
> Fix version number in VS2019 solution files

- DirectXTex/DirectXTexConvert.cpp
Shifting uint32_t by an amount larger than 31 has undefined behavior across different platforms, and while AMD64 returns 0 when there's overflow, some platforms — including Direct3D shaders and PowerPC — only use the lower 5 bits.
This may cause floats with exponent smaller than -33 to be converted to 7e3 incorrectly, resulting in non-zero values when the number is totally too small to be represented as 7e3, and for 6e4 this may happen when the exponent is smaller than -37.
I've noticed this issue when I was testing similar code for 20e4 in a shader — when the float32 value was zero, the shift amount was 113 — which has a remainder of 17 when divided by 32 — so the 0x800000 part was kept, and I got 8 instead of 0 in the result.
This fix limits the shift amount to 24, which is the maximum …
> Prevent shift overflow in FloatTo7e3/FloatTo6e4 denormal conversion

- .gitignore
- DirectXTex/BC.cpp
- DirectXTex/BC.h
- DirectXTex/BC4BC5.cpp
- DirectXTex/BC6HBC7.cpp
- DirectXTex/BCDirectCompute.cpp
- DirectXTex/CMakeLists.txt
- DirectXTex/CMakeSettings.json
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexCompress.cpp
- DirectXTex/DirectXTexCompressGPU.cpp
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexD3D11.cpp
- DirectXTex/DirectXTexD3D12.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexFlipRotate.cpp
- DirectXTex/DirectXTexHDR.cpp
- DirectXTex/DirectXTexImage.cpp
- DirectXTex/DirectXTexMipmaps.cpp
- DirectXTex/DirectXTexMisc.cpp
- DirectXTex/DirectXTexNormalMaps.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexPMAlpha.cpp
- DirectXTex/DirectXTexResize.cpp
- DirectXTex/DirectXTexTGA.cpp
- DirectXTex/DirectXTexUtil.cpp
- DirectXTex/DirectXTexWIC.cpp
- DirectXTex/filters.h
With VS 2019 Update 1 supporting the clang/LLVM toolset, I've formally added CMake files as well as addressed a number of clang warnings.
> Add CMake project and fix clang warnings

- DDSTextureLoader/DDSTextureLoader.cpp
- DirectXTex/DirectXTexD3D11.cpp
- WICTextureLoader/WICTextureLoader.cpp
If you pass a 'non-null' value to the DDS or WIC texture loaders, but when calling the ``Ex`` version you provide a ``bindFlags`` without the ``D3D11_BIND_SHADER_RESOURCE`` then it will fail when it calls ``CreateShaderResourceView``.
This PR adds validation early in the function to catch this rather than failing later on...
>   Ex texture loaders updated with additional parameter validation

- ScreenGrab/ScreenGrab.cpp
- ScreenGrab/ScreenGrab.h
- ScreenGrab/ScreenGrab12.cpp
- ScreenGrab/ScreenGrab12.h
With the new 'flip' style presentation model for Windows 10 or later, you don't actually use ``*_SRGB`` on the backbuffer format. Therefore, the resulting ``PNG`` screenshot would be washed out.
This adds a new optional paraemeter to allow forcing the sRGB metadata.
> Added optional forceSRGB parameter to SaveWICTextureToFile

- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexHDR.cpp
- DirectXTex/DirectXTexTGA.cpp
- DirectXTex/DirectXTexWIC.cpp
In the various Image readers, formats without alpha can be converted to formats with alpha in various cases. When this is done, the alpha is set to all 1. For example, when loading a 24bpp bitmap there is no 24pp DXGI format so we expand it to RGBA32.
This change causes the ``Metadata`` alpha mode to be set to ``TEX_ALPHA_MODE_OPAQUE`` in those specific loading conversion cases.
> Return TEX_ALPHA_MODE_OPAQUE metadata if the reader knows it returned opaque alpha

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexTGA.cpp
- Texconv/texconv.cpp
Three distinct changes in this pull request:
First, the TGA writer now includes the official TGA 2.0 footer in all cases. This is recommended in the spec. It does not impact the ability of older codecs to read the content of the file.
Second, when reading a TGA, if there is a TGA 2.0 extension area present I use the AttributeType to set the alpha mode in the returned metadata--unless the reader already set it to OPAQUE due to format.
Third, if the caller provides the new optional metadata parameter to the TGA writer, it will write the TGA 2.0 extension area. This extension area includes AttributeType derived from the metadata alpha mode, the time stamp, a software ID of "DirectXTex", and a software version of ``DIRECTX_TEX_VERSION``.  If the source format was ``DXGI_FORMAT_*_SRGB`` I also …
> Update TGA codec for TGA 2.0

- Texconv/texconv.cpp
DirectXTex has generalized support for BC image sizes so it can support non-multiple-of-4 image sizes and properly BC them. However, Direct3D itself can only create a BC resource if the top-most miplevel is a multiple-of-4 in both width and height.
As such, some DDS files have been written that can't actually be loaded as textures. For example, a 1x1 BC compressed DDS.  With the new ``-fixbc4x4`` switch, such BC compressed images are rounded up to fix, although this process invalidates any existing mipchain.
> texconv: added -fixbc4x4 switch

- DDSTextureLoader/DDSTextureLoader.h
- DDSTextureLoader/DDSTextureLoader12.h
- WICTextureLoader/WICTextureLoader.h
- WICTextureLoader/WICTextureLoader12.h
I've had this in my codebase for a while and though it might be useful: the only thing that prevents DDSTextureLoader.h and DDSTextureLoader12.h being included from the same file is the definition for DDS_ALPHA_MODE enum which can be avoided with a pair of #ifdef-s/#define-s.
> Allow DDSTextureLoader.h and DDSTextureLoader12.h to be included together (same for WICTextureLoader.h/WICTextureLoader12.h)

- DirectXTex/DirectXTexDDS.cpp
There are files that use this FourCC in the wild, but I do not know what tool was used to create them.
> Support reading files that use a 'BC7\0' FourCC

- CMakeLists.txt
- CMakeSettings.json
UTF-8 without a BOM is recommended for file formatting. This is the most compatible with various tools and also takes up the least amount of space (though in this case it only saves 4 bytes).
> Remove BOM from two files

- DDSTextureLoader/DDSTextureLoader11.cpp
- DDSTextureLoader/DDSTextureLoader11.h
- DDSTextureLoader/DDSTextureLoader12.cpp
- DDSTextureLoader/DDSTextureLoader9.cpp
- DDSTextureLoader/DDSTextureLoader9.h
- DirectXTex/DDS.h
- ScreenGrab/ScreenGrab11.cpp
- ScreenGrab/ScreenGrab11.h
- ScreenGrab/ScreenGrab12.cpp
- ScreenGrab/ScreenGrab9.cpp
- ScreenGrab/ScreenGrab9.h
- Texconv/texconv.cpp
- WICTextureLoader/WICTextureLoader11.cpp
- WICTextureLoader/WICTextureLoader11.h
- WICTextureLoader/WICTextureLoader12.cpp
- WICTextureLoader/WICTextureLoader12.h
- WICTextureLoader/WICTextureLoader9.cpp
- WICTextureLoader/WICTextureLoader9.h
DDSTextureLoader9 & WICTextureLoader9 added to DirectXTex
Added ``WIC_LOADER_FIT_POW2`` and ``WIC_LOADER_MAKE_SQUARE`` to WICTextureLoader (also in DirectX Tool Kits)
> DDSTextureLoader renamed to DDSTextureLoader11
> ScreenGrab renamed to ScreenGrab11
> WICTextureLoader renamed to WICTextureLoader11
> Direct3D 9 versions of texture loaders

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexWIC.cpp
- WICTextureLoader/WICTextureLoader11.cpp
- WICTextureLoader/WICTextureLoader12.cpp
Added ``WIC_FLAGS_DEFAULT_SRGB`` to control behavior without any colorspace metadata.
For the PNG loader, added a special case of gAMA indicating sRGB without an sRGB chunk.
> Added WIC_FLAGS_DEFAULT_SRGB flag

- DirectXTex/BC.cpp
- DirectXTex/BC.h
- DirectXTex/BC4BC5.cpp
- DirectXTex/BC6HBC7.cpp
- DirectXTex/BCDirectCompute.cpp
- DirectXTex/BCDirectCompute.h
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTex.inl
- DirectXTex/DirectXTexCompress.cpp
- DirectXTex/DirectXTexCompressGPU.cpp
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexFlipRotate.cpp
- DirectXTex/DirectXTexImage.cpp
- DirectXTex/DirectXTexMipmaps.cpp
- DirectXTex/DirectXTexMisc.cpp
- DirectXTex/DirectXTexNormalMaps.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexPMAlpha.cpp
- DirectXTex/DirectXTexResize.cpp
- DirectXTex/DirectXTexTGA.cpp
- DirectXTex/DirectXTexUtil.cpp
- DirectXTex/DirectXTexWIC.cpp
- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
There are many different flags in DirectXTex, and they all use DWORD so it's easy to get the wrong flag.
This PR changes all the flags in DirectXTex's public interface to strongly-typed flags via the ``DEFINE_ENUM_FLAG_OPERATORS`` macro from winnt.h--this is what Direct3D uses to type flags.
**This is a breaking change** but it's fairly easy to fix them up as you can see in the ``texconv`` et al. tools. You can also check out the [test suite](https://github.com/walbourn/directxtextest/pull/13) for examples.
> Switched to using strongly typed flags

- CMakeLists.txt
- Texassemble/texassemble.cpp
- Texconv/ExtendedBMP.cpp
- Texconv/PortablePixMap.cpp
- Texconv/Texconv_Desktop_2017.vcxproj
- Texconv/Texconv_Desktop_2017.vcxproj.filters
- Texconv/Texconv_Desktop_2019.vcxproj
- Texconv/Texconv_Desktop_2019.vcxproj.filters
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
D3DX9 supported reading ``PPM`` and ``PFM`` files, and writing ``PFM`` files. These formats are 80s-era 'minimal viable format' kinds of things, and not really interesting to put into DirectXTex itself.
That said, I wanted to support these in texconv for conversion so I can consider it a 100% replacement for all things D3DX9 did. Therefore I implemented them 'inline' in texconv. This meets my goals without requiring a lot of effort to fuzz-test and validate a formal PPM/PFM codec.
It turns out that PFM in particular is used for academic image sharing (like lightprobes) so this seems like a useful feature.
> Portable PixMap reader/writers for texconv

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexDDS.cpp
- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
The DDSTextureLoader modules have checks for 'maximum required' size bounds for rejecting extremely large ``.DDS`` files that probably won't work with Direct3D at runtime. DIrectXTex's DDS codec being intended for tools didn't have such checks in case you wanted to convert some weirdly large .DDS file.
While I generally encourage using DDSTextureLoader for run-time texture loading scenarios, some people prefer to use DirectXTex. Also for viewer tools, you probably don't want to try to load unbounded size images anyhow.
This PR adds bounds checks to the DDS codec, but you can opt-out of these with a new loading flag for tools where you want to support these. I use this new flag for the command-line tools, although in practice only the x64 native versions of those tools are likely to be …
> DirectXTex updated with DDS_FLAGS_ALLOW_LARGE_FILES

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTex.inl
- DirectXTex/DirectXTexTGA.cpp
Normally the TGA reader handles the case of finding an all zero alpha channel to mean "opaque" which results in setting all the alpha values to 255. This is fine and deals with some wierd older TGA files, unless you really want an all zero alpha channel.
This adds a new flag ``TGA_FLAGS_ALLOW_ALL_ZERO_ALPHA`` to let you disable this behavior. ``TGA_FLAGS_NONE`` keeps the original behavior.
Also added ``TGA_FLAGS_BGR`` so you can get back BGRX (for 24bpp TGAs) or BGRA (32bpp TGAs) instead of always getting back RGBA.
> The TGA reader has had no explicit option flags before now. I've added the flags to all the TGA functions to be consistent with DDS/WIC, although save don't use the flags yet. Also added inlines so older clients do not break.
> Added TGA_FLAGS for TGA reader

- DDSTextureLoader/DDSTextureLoader9.cpp
- DDSTextureLoader/DDSTextureLoader9.h
- WICTextureLoader/WICTextureLoader9.cpp
- WICTextureLoader/WICTextureLoader9.h
Added Ex versions of these DX9 loaders so you can provide ``usage`` and ``pool`` parameters for the created textures.
> Added Ex variants to DX9 DDSTextureLoader, WICTextureLoader

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexTGA.cpp
Adds ``TGA_FLAGS_FORCE_SRGB``, and ``TGA_FLAGS_FORCE_LINEAR`` to the TGA writer when using TGA 2.0 metadata.
Adds ``TGA_FLAGS_DEFAULT_SRGB``, ``TGA_FLAGS_IGNORE_SRGB`` and use of TGA 2.0 metadata for colorspace to the TGA reader.
> TGA flags for sRGB colorspace in TGA 2.0 extension area

- .nuget/directxtex-config.cmake.in
- CMakeLists.txt
This PR updates the CMake support in DirectXTex to support ``find_package(directxtex CONFIG)``:
```
find_package(directxtex CONFIG REQUIRED)
target_link_libraries(foo Microsoft::DirectXTex)
```
> CMake package support 

- DDSView/ddsview.cpp
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexP.h
- Texassemble/AnimatedGif.cpp
- Texassemble/texassemble.cpp
- Texconv/ExtendedBMP.cpp
- Texconv/PortablePixMap.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
Reviewed all the C++ standard library header usage and normalized usage for improved conformance.
* ``algorithm`` was used internally, but not in the public interface
* ``size_t`` requires ``cstddef``
* ``memcpy``, ``memcpy_s`` is officially in ``cstring``
* Use ``cassert`` instead of ``assert.h``, ``ctime`` instead of ``time.h``
* ``std::move`` is in ``utility``
> The non-standard malloc.h is still being included for ``_aligned_malloc`` / ``_aligned_free``. To be conformant, I should update it to use ``aligned_alloc`` and ``free`` when building for C++17 which is in ``cstdlib``.
Also trimmed trailing whitespace in these files.
> Code review for standard library header usage

- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
Added ``-r:keep`` as an option for recursive copying of the directory structure to the output directory.
```
texconv -r:keep -o targetdir <source>\*png
```
If you use ``-r`` or ``-r:flatten``, it copies the outputs all to the same directory as it did before.
> texconv support for -r:keep

- Texconv/texconv.cpp
Allows arbitrary swizzles for source data:
```
texconv -swizzle rgba <filename>
```
```
texconv -swizzle rrra <filename>
```
```
texconv -swizzle bgra <filename>
```
```
texconv -swizzle aaaa <filename>
```
```
texconv -swizzle zzwx <filename>
```
etc.
> texconv -swizzle option

- DirectXTex/DirectXTexD3D12.cpp
- ScreenGrab/ScreenGrab12.cpp
It is unable to call `GetHeapProperties` for reserved resources. But such info required only for `READBACK` resources optimization, capture code should not fail for reserved resources in this case.
```
D3D12 ERROR: ID3D12Resource2::ID3D12Resource::GetHeapProperties: GetHeapProperties can not be called on a resource created with the CreateReservedResource API. [ RESOURCE_MANIPULATION ERROR #901: GETHEAPPROPERTIES_INVALIDRESOURCE]
```
Invalid desc for resolved resource copied from the original multisample resource with `Alignment = D3D12_DEFAULT_MSAA_RESOURCE_PLACEMENT_ALIGNMENT`, which fails creation call.
> Fix of CaptureTexture for Reserved and MultiSample resources

- DirectXTex/DirectXTexDDS.cpp
Previously condition (metadata.format == DXGI_FORMAT_B5G6R5_UNORM) is always false so
check format before replace it with DXGI_FORMAT_R8G8B8A8_UNORM
> Fix CONV_FLAGS_NOALPHA flag for 16bpp format

- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
This updates the processing of ``-flist`` file list files to support wildcards. It also supports using `-` to indicate 'remove' file for removing specific instances of a file from the wildcard match.
> texassemble/texconv/texdiag updated with improved -flist support

- .nuget/DirectXTex-config.cmake.in
These `find_dependency` calls in the config file need to mirror the `find_package` calls in the `CMakeLists.txt`, or else the configure step will fail with missing dependencies.
https://github.com/microsoft/DirectXTex/blob/6c6c910af327b182d5cd610dc3d2f7ec284f7629/CMakeLists.txt#L139
https://github.com/microsoft/DirectXTex/blob/6c6c910af327b182d5cd610dc3d2f7ec284f7629/CMakeLists.txt#L161-L162
> Add missing `find_dependency` calls to cmake config file

- DirectXTex/Shaders/CompileShaders.cmd
When compiling shaders, if your file path contains spaces it will fail to compile shaders, this PR fixes that.
> Fix shaders not compiling with spaces in the path

- DirectXTex/DirectXTex.inl
I quote:
"A function or static data member declared with the constexpr or consteval specifier is implicitly an inline function or variable ([dcl.inline])"
from: https://eel.is/c++draft/dcl.constexpr
Also, analyzing something alike the following:
```
#include <cstdio>
#include <random>
struct Type {
int a;
};
constexpr auto operator+(const Type& a, const Type& b) {
return a.a + b.a;
}
int main()
{
auto a = Type{rand()};
auto b = Type{rand()};
auto c = a + b;
}
```
with C++ Insights, inline will be implied regardless, so there's no reason for it to be in the code base itself.
> Remove inline specifier from constexpr functions

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexCompress.cpp
- DirectXTex/DirectXTexCompressGPU.cpp
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexFlipRotate.cpp
- DirectXTex/DirectXTexImage.cpp
- DirectXTex/DirectXTexMipmaps.cpp
- DirectXTex/DirectXTexMisc.cpp
- DirectXTex/DirectXTexNormalMaps.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexPMAlpha.cpp
- DirectXTex/DirectXTexResize.cpp
- DirectXTex/DirectXTexTGA.cpp
- DirectXTex/DirectXTexUtil.cpp
- DirectXTex/DirectXTexWIC.cpp
- DirectXTex/d3dx12.h
- DirectXTex/filters.h
- ScreenGrab/ScreenGrab11.cpp
- ScreenGrab/ScreenGrab12.cpp
- ScreenGrab/ScreenGrab9.cpp
- WICTextureLoader/WICTextureLoader11.cpp
- WICTextureLoader/WICTextureLoader12.cpp
- WICTextureLoader/WICTextureLoader9.cpp
Per the C++ Standard:
> the identifiers that begin with an underscore followed by an uppercase letter are reserved;
I had this in my backlog for some time, but never got around to it until now. Clang v13 (which is in VS 2022 Update 1) has added a new warning for this case: ``-Wreserved-identifier``
In addition, I've made the ``EncodeDDSHeader`` function public per request.
> Convert internal functions to use Internal namespace instead of leading underscore

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexUtil.cpp
- DirectXTex/DirectXTexWIC.cpp
- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
HEIF/HEIC and WEBP are not supported by 'native' WIC codecs, but are supported by official Microsoft installable codecs from the Microsoft Store. This updates the command-line tools to support these.
> WEBP is only supported for reading. HEIF/HEIC is supported for read and write.
> Add support for HEIF and WEBP to command-line tools

- Texassemble/texassemble.cpp
* Fixed layout issue with *v-cross* which was in the wrong order compared to the Unity reference
* Added *v-cross-fnz* variant which rotates the negative Z face 180 so it looks consistent with cross images from AMD CubeMapGen
* Added *h-tee* layout variant
> texassemble updates for cubemap image generation

- Texassemble/texassemble.cpp
* Added commands to create cubemap from a image
`cube-from-hc` for h-cross layout
`cube-from-vc` for v-cross layout
`cube-from-vc-fnz` for v-cross layout flipping the -Z face
`cube-from-ht` for h-tee layout
`cube-from-hs` for h-strip layout
`cube-from-vs` for v-strip layout
* Changed help message for array-strip (from "creates ..." to "create ...")
> Texassemble updates for cubemap generation from a image

- CMakeLists.txt
- CMakePresets.json
CMake 3.20 allows the removal of some string hacks for ``/Wall`` and ``/GR-`` for ``CMAKE_CXX_FLAGS``.
Also integrates the test suite if present. CTest support added to the test suite in this PR: https://github.com/walbourn/directxtextest/pull/22
> CMake update for version 3.20 

- .nuget/directxtex_desktop_2019.nuspec
- .nuget/directxtex_desktop_win10.nuspec
- .nuget/directxtex_uwp.nuspec
- HISTORY.md
- README.md
* ARM/ARM64 platform fix for 16bpp pixel conversion
* Updated D3DX12 internal copy with latest changes from DirectX-Headers GitHub
* CMake project updated to require 3.20 or later
* CMake and MSBuild project updates
* Added Azure Dev Ops Pipeline YAML files
* ``Auxiliary`` folder added with DirectXEXR.h/.cpp optional module
* Test suite updated with CTest support
* Spectre-mitigated libraries added to NuGet packages
* texassemble: added commands *v-cross-fnz*, *h-tee*, and *cube-from-\**
* texconv: Fixed minor printf output issue
> December 15, 2022

- DDSTextureLoader/DDSTextureLoader11.cpp
- DDSTextureLoader/DDSTextureLoader12.cpp
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexD3D11.cpp
- DirectXTex/DirectXTexD3D12.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexImage.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexUtil.cpp
**ConvertToSinglePlane** did not validate that the input images meet the height alignment requirements for the source format. This can result in a memory overwrite if untrusted content is passed from the DDS loader directly to this function.
This PR also includes additional hardening for the DDS loader, ComputePitch, and DDSTextureLoader modules to validate width & height requirements for planar video textures.
> ConvertToSinglePlane memory overrwrite bug fix

- DDSTextureLoader/DDSTextureLoader12.cpp
- DirectXTex/DirectXTexD3D12.cpp
- WICTextureLoader/WICTextureLoader12.cpp
- build/DirectXTex-GitHub-MinGW.yml
When **SetEnableGPUBasedValidation** is enabled on Windows, the initial state for a resource will result in a harmless but noisy warning.
```
D3D12 WARNING: ID3D12Device::CreateCommittedResource: Ignoring InitialState D3D12_RESOURCE_STATE_COPY_DEST. Buffers are effectively created in state D3D12_RESOURCE_STATE_COMMON. [ STATE_CREATION WARNING #1328: CREATERESOURCE_STATE_IGNORED]
```
The fix is to use the ``COMMON`` state initially and allow it to promote automatically.
> Clean up GPU-based validation warnings

- .nuget/directxtex_desktop_2019.nuspec
- .nuget/directxtex_desktop_win10.nuspec
- .nuget/directxtex_uwp.nuspec
- CMakeLists.txt
- DirectXTex/DirectXTex.h
- HISTORY.md
- LICENSE
- README.md
* Fixed memory overwrite bug in **ConvertToSinglePlane** that can lead to a potential security issue for untrusted planar video format DDS files
* Make sure ScratchImage zero-fills image memory
* Fix DirectX12 GPU-validation warnings for texture loaders
* Minor fix for non-Win32 builds
* ddsview: Updated sample app with a ``-forcesrgb`` command-line switch
> January 31, 2023

- .nuget/directxtex_desktop_2019.nuspec
- .nuget/directxtex_desktop_win10.nuspec
- .nuget/directxtex_uwp.nuspec
- CMakeLists.txt
- DDSTextureLoader/DDSTextureLoader11.cpp
- DDSTextureLoader/DDSTextureLoader12.cpp
- DDSView/ddsview.cpp
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexD3D11.cpp
- DirectXTex/DirectXTexD3D12.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexImage.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexUtil.cpp
- HISTORY.md
- LICENSE
- README.md
- WICTextureLoader/WICTextureLoader12.cpp
- build/DirectXTex-GitHub-MinGW.yml
* Fixed memory overwrite bug in **ConvertToSinglePlane** that can lead to a potential security issue for untrusted planar video format DDS files
* Make sure ScratchImage zero-fills image memory
* Fix DirectX12 GPU-validation warnings for texture loaders
> January 31, 2023 [Xbox Variant]

- CMakeLists.txt
Needed to support **directxtex** VCPKG port with a **dx11** feature that can be removed for scenarios where you don't want to use the FXC.EXE compiler.
> CMake bug fixed if BUILD_DX11=OFF but BUILD_TOOLS=ON

- .nuget/directxtex_desktop_2019.nuspec
- .nuget/directxtex_desktop_win10.nuspec
- .nuget/directxtex_uwp.nuspec
- HISTORY.md
- README.md
* Fix for `SRGB_IN` / `SRGB_OUT` flag handling for GPU BC7 compressor
* Fix to clamp negative values when encoding with the GPU BC6H compressor
* GPU BC6H/BC7 encoder updated to make optional use of DirectCompute 5.0
* CMake project updates
* Code review
* Retired VS 2017 legacy Xbox One XDK projects
* texassemble/texconv/texdiag: Updated to support Windows or UNIX-style path separators
> March 30, 2023

- .nuget/directxtex_desktop_2019.nuspec
- .nuget/directxtex_desktop_win10.nuspec
- .nuget/directxtex_uwp.nuspec
- DirectXTex/BCDirectCompute.cpp
- DirectXTex/Shaders/BC6HEncode.hlsl
- DirectXTex/Shaders/CompileShaders.cmd
- HISTORY.md
- README.md
- Texassemble/Texassemble_Desktop_2019.vcxproj
- Texassemble/Texassemble_Desktop_2022.vcxproj
- Texassemble/texassemble.cpp
- Texconv/Texconv_Desktop_2019.vcxproj
- Texconv/Texconv_Desktop_2022.vcxproj
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
- Texdiag/texdiag_Desktop_2019.vcxproj
- Texdiag/texdiag_Desktop_2022.vcxproj
* Fix for `SRGB_IN` / `SRGB_OUT` flag handling for GPU BC7 compressor
* Fix to clamp negative values when encoding with the GPU BC6H compressor
* GPU BC6H/BC7 encoder updated to make optional use of DirectCompute 5.0
* CMake project updates
* Code review
* Retired VS 2017 legacy Xbox One XDK projects
* texassemble/texconv/texdiag: Updated to support Windows or UNIX-style path separators
> March 30, 2023 [Xbox Variant]

- DirectXTex/d3dx12.h
* Added new types from the latest DirectX SDK Agility SDK release (1.610)
* Switched to using ``D3D12_SDK_VERSION`` for guards instead of Windows SDK defines
* Minor SAL fixes
> D3DX12 updated to latest version

- build/DirectXTex-config.cmake.in
Now that the CMake file is using the OpenMP package, it needs a `find_dependency` in the config file.
> Update CMake config file to include OpenMP

- DirectXTex/DirectXTex.inl
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexUtil.cpp
- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
In the *DirectX Agility SDK* 1.610, there is a new DXGI format ``DXGI_FORMAT_A4B4G4R4_UNORM`` to support D3D11on12. This PR adds support to DirectXTex for this format.
> Since there is no Direct3D 9 direct-equivalent format, this format is always read/written in DDS files using the `DX10` extension header.
> Add support for new DXGI 16bpp format

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexConvert.cpp
We already have filter flags for copying RED, GREEN, or BLUE channels for RGB to R conversions, as well as RED | GREEN, GREEN | BLUE, and RED | BLUE for RGB to RG conversions.
This adds a flag to allow RED, GREEN, BLUE, or ALPHA for RGBA to R conversions, and adds RED | ALPHA, GREEN | ALPHA, and BLUE | ALPHA combinations for RGBA to RG conversions.
> Add TEX_FILTER_RGB_COPY_ALPHA for RGBA to R and RGBA to RG convert

- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
Fixed output from texassemble, texdiag, and texconv when getting an error string.
> tex tools: remove newlines from FORMAT_MESSAGE_FROM_SYSTEM

- CMakeLists.txt
Support for "SHA256" hashing of PDBs is required for SDL compliance, and is supported by VS 2019 or later. Support for this switch was added to clang/LLVM for Windows v16 which is coming in VS 2022 17.6.
> CMake update to use /ZH:SHA_256 for clang v16 or later

- CMakeLists.txt
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTex.inl
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexUtil.cpp
- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
- build/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
- build/DirectXTex-GitHub-CMake-Xbox.yml
- build/DirectXTex-GitHub-GDK-Dev17.yml
- build/DirectXTex-GitHub-GDK.yml
- build/DirectXTex-GitHub-SDK-prerelease.yml
- build/DirectXTex-GitHub-SDK-release.yml
- build/DirectXTex-GitHub.yml
- build/DirectXTex-config.cmake.in
* ``TEX_FILTER_RGB_COPY_ALPHA`` flag
* Support for ``DXGI_FORMAT_A4B4G4R4_UNORM``
* GetErrorDesc fix for command-line tools
* CMake fix for OpenMP dependency and ``/ZH:SHA_256`` for clang v16
> Also need a workaround applied for a problem with NuGet 6.6 and NuGetCommand@2 using custom.
> Update Xbox variant for changes for May 2023

- Texconv/texconv.cpp
Adds ``-tgazeroalpha`` switch to add the use of ``TGA_FLAGS_ALLOW_ALL_ZERO_ALPHA`` for loading of TGA files with all zero alpha channels as all zeros.
Related to PR [197](https://github.com/microsoft/DirectXTex/pull/197).
> texconv: Added tgazeroalpha switch for some legacy TGA files

- Texconv/texconv.cpp
This proposes adding support for the `.DDX` file format you can find in some Xbox Arcade ported games like Halo Wars and Dungeon Defender.
The `.DDX` format is functionally identical to the `.DDS` format and does not require any changes to the `CODEC_DDS`.
The changes has been compiled and tested in the command-line tool `texconv.exe`
> Add .DDX Support

- CMakeLists.txt
- DirectXTex/d3dx12.h
When building with CMake and VS 2022 Update 5 or later, I make use of ``/Zc:templateScope`` for conformance validation. This is, however, not compatible with the Windows SDK prior to the Windows SDK (22000) build.
> Also fixes a build break in the Windows SDK preview validation pipelines.
> Fix CMake problem with /Zc:templateScope on older Windows SDKs

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexDDS.cpp
- Texconv/texconv.cpp
The "DXT5nm" format is a "swizzled" DXT5/BC3 variant supported by a number of tools. It's intended to encode normal maps using BC3 which is supported on all Direct3D Hardware Feature levels rather than BC4/BC5 which originally was an ATI only extension and then part of Direct3D Hardware Feature Level 10.0. It encodes the 'x' as the alpha channel, 'y' as the green channel, sets the red channel to 1.0, and the blue channel to 0 to get good quality compression of both components.
The "RXGA" format is a "swizzled" DXT5/BC3 variant supported by a number of tools and popularized by Doom 3. It swaps the 'r' and 'a' channels, leaving 'g' and 'b' in place. This is normally written as "DXT5", but if ``-f RXGB -dx9`` is used, then it will write using the FourCC "RXGB" instead.
The PR also adds …
> texconv: Added support for DXT5nm and RXGB DXT5 format variants

- build/DirectXTex-config.cmake.in
The CMakeLists.txt no longer mandates both **directxmath** and **directx-headers** packages be found unless building with MinGW or for Linux. This fixes the behavior for CMake clients consuming this package from VCPKG.
> CMake target file fix

- CMakeLists.txt
- build/DirectXTex-config.cmake.in
WIth the changes to make use of DirectXMath & DirectX-Headers 'optional' for VCPKG scenarios unless using MinGW -or- Linux, the generated targets file needed more robust handling of these targets.
Also made sure that explicit 'scope' is used consistently with all CMake ``target_`` commands.
> This was noticed when building ``rsm-bsa`` with VCPKG as this uses DirectXTex, but not DirectXMath.
> CMake targets fixes for optional vs. required packages

- DirectXTex/d3dx12.h
Also fixes a -Wold-school-cast warning from clang.
> D3DX12 update to fix build errors when using preview Windows SDKs

- DirectXTex/DirectXTexDDS.cpp
These files have an incorrectly populated DDS_PIXELFORMAT structure, all fields except the dwFourCC field are set to zero.
The following zip file contains some sample files for your test suite:  [UT2004 DDS samples.zip](https://github.com/microsoft/DirectXTex/files/11962909/UT2004.DDS.samples.zip)
The files are originally from [this](https://forums.getpaint.net/topic/22473-some-dds-files-fail-to-load-examples-included/) thread on the Paint.NET forum.
> Add support for reading Unreal Tournament 2004 DDS files

- DirectXTex/BCDirectCompute.cpp
Fixed a small bug that was missed in #326 where the code was over-validating the format information internally for BC7 compression scenarios using ``SRGB`` override flags.
> Remove overvalidation bug for BC7 GPU compressor with -srgb

- CMakeLists.txt
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexHDR.cpp
- DirectXTex/DirectXTexTGA.cpp
- DirectXTex/DirectXTexWIC.cpp
- build/DirectXTex-GitHub-CMake-Dev17.yml
- build/DirectXTex-GitHub-CMake.yml
Some usage scenarios build the library with ``/Zc:wchar_t-`` but mix both ``unsigned short*`` and ``wchar_t*`` client usage. For this *opt-in* build scenario, the library will link with both the non-native and native ``wchar_t``.
> Also fixes some Code Analysis warnings as you can't use ``_In_opt_`` with ``std::function<>``.
> Add NO_WCHAR_T build option to CMake

- CMakeLists.txt
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexCompress.cpp
- DirectXTex/DirectXTexCompressGPU.cpp
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexHDR.cpp
- DirectXTex/DirectXTexTGA.cpp
- DirectXTex/DirectXTexWIC.cpp
- DirectXTex/DirectXTexXbox.h
- DirectXTex/DirectXTexXboxDDS.cpp
- build/DirectXTex-GitHub-CMake-Dev17.yml
- build/DirectXTex-GitHub-CMake.yml
* Add NO_WCHAR_T build option to CMake (#384)
* Add CompressEx and ConvertEx methods that report progress (#375)
* Update Xbox extensions for NO_WCHAR_T and DDSMetaData changes
> Update Xbox with latest changes from August 2023 work

- DirectXTex/DirectXTexP.h
The CMake scenario already disables the new clang v16 warning, but if you upgrade the VCXPROJ project to clangcl, it reappears.
> Suppress some additional clang v16 warnings when upgrading to clangcl

- .nuget/directxtex_uwp.nuspec
- CMakePresets.json
- DirectXTex/DirectXTex_Windows10_2019.vcxproj
- DirectXTex/DirectXTex_Windows10_2022.vcxproj
- DirectXTex_Windows10_2019.sln
- DirectXTex_Windows10_2022.sln
- build/DirectXTex-GitHub-CMake-Dev17.yml
- build/DirectXTex-GitHub-CMake.yml
- build/DirectXTex-GitHub-Dev17.yml
- build/DirectXTex-GitHub.yml
32-bit ARM support is being deprecated for the UWP platform, and support is being removed from newer ARM-based CPUs and the Windows 11 OS.
> 32-bit ARM was never officially supported for Win32 desktop development.
See [Microsoft Learn](https://learn.microsoft.com/windows/arm/arm32-to-arm64)
> AArch32 (ARM32) architecture deprecation

- DirectXTex/DirectXTexDDS.cpp
This is a common issue with the legacy DX 9 textures used by the game FlatOut 2.
The other DDS header fields are correct, so it is probably a bug in the program that created those files.
Fixes #392
> Support reading files with a DDS_PIXELFORMAT size of 24

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexDDS.cpp
- Texconv/texconv.cpp
In #371 the DDS reader was updated to allow the header to contain a DDPIXELFORMAT.dwSize of 0 and a valid FourCC code.
In #393 the DDS reader was updated to allow the header to contain a DDPIXELFORMAT.dwSize of 24 as long as the DDS_HEADER.dwSize size was correct.
This moves both of those cases to require the ``DDS_FLAGS_PERMISSIVE`` flag or the reader will reject them as invalid DDS files which was the original behavior.
Furthermore, with the ``DDS_FLAGS_PERMISSIVE`` flag the reader will also accept DDS_HEADERs with mipCounts that are too large for the input size. These will be bounded to the *correct* value. The most common file case here is a mipcount that is one too large, but this handles any too large mipCount.
The **texconv** tool now accepts ``-permissive`` as a command-line …
> DDS_FLAGS_PERMISSIVE flag to allow some file variants with header bugs

- build/DirectXTex-GitHub-MinGW.yml
- build/DirectXTex-GitHub-Test-Dev17.yml
The latest **windows-2022** ADO image no longer includes the Ninja build tool by default. It had been pulled in by another component as a dependency but is no longer there. The official solution is to install ninja using the Chocolatey package manager which part of the base image.
The latest update upgraded MinGW-W64 to 12.2, so I no longer need to explicitly install it for that pipeline.
> Update build pipelines for recent changes to windows-2022 ADO images

- Texassemble/texassemble.cpp
- Texconv/flist.txt
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
The file list processing failed with filenames with spaces in them. This fixes the parsing to be line-by-line explicitly.
> Fixed -flist handling for filenames with spaces

- .nuget/directxtex_desktop_2019.nuspec
- .nuget/directxtex_desktop_win10.nuspec
- .nuget/directxtex_uwp.nuspec
- CMakeLists.txt
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexDDS.cpp
- HISTORY.md
- README.md
- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
- build/DirectXTex-GitHub-MinGW.yml
- build/DirectXTex-GitHub-Test-Dev17.yml
* New ``DDS_PERMISSIVE_FLAG`` to allow reading of various DDS DX9 file variants
* *breaking change* required to accept reading *Unreal Tournament 2004* DDS files
* Allows cases where DDS_HEADER size is incorrectly set to 24
* Allows cases where DDPIXELFORMAT size is incorrectly set to 24
* Allows cases where DDS_HEADER.MipMapCount is set to the wrong value
* texassemble/texconv/texdiag: -flist option updated to support filenames with spaces
* texconv: -permissive switch added to opt-in use of new flag when reading DDS files
> October 2023 release [Xbox variant]

- Texconv/PortablePixMap.cpp
The *Netpbm* library uses 32-bit signed ints and any value that's negative is considered 'too big' which means it effectively bounds by the size of ``INT32_MAX``. I added an explicitly validation of width/height for PPM and PFM for that max value.
> texconv: Updated PPM/PFM reader with explicit bounds check

- Auxiliary/DirectXTexXbox.h
- Auxiliary/DirectXTexXboxD3D11X.cpp
- Auxiliary/DirectXTexXboxD3D12X.cpp
- Auxiliary/DirectXTexXboxDDS.cpp
- Auxiliary/DirectXTexXboxDetile.cpp
- Auxiliary/DirectXTexXboxImage.cpp
- Auxiliary/DirectXTexXboxTile.cpp
- CMakeLists.txt
- CMakePresets.json
- DirectXTex/DirectXTex_GDK_2019.vcxproj
- DirectXTex/DirectXTex_GDK_2022.vcxproj
- DirectXTex/DirectXTex_GDK_2022.vcxproj.filters
- DirectXTex/DirectXTex_GXDK_PC_2019.vcxproj
- DirectXTex/DirectXTex_GXDK_PC_2019.vcxproj.filters
- DirectXTex/DirectXTex_GXDK_PC_2022.vcxproj
- DirectXTex/DirectXTex_GXDK_PC_2022.vcxproj.filters
- DirectXTex_GXDK_PC_2019.sln
- DirectXTex_GXDK_PC_2022.sln
- NuGet.Config
- build/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
- build/DirectXTex-GitHub-CMake-Xbox.yml
- build/DirectXTex-GitHub-GDK-Dev17.yml
- build/DirectXTex-GitHub-GDK.yml
- build/DirectXTex-GitHub-SDK-prerelease.yml
- build/DirectXTex-GitHub-SDK-release.yml
- build/Directory.Build.props
- build/SetupBWOI.targets
The Xbox extensions were housed in their own **xbox** branch, but this PR moves that into the mainline using the *Auxiliary* folder.
> Merge Xbox extensions into mainline as Auxiliary

- DirectXTex/DirectXTexHDR.cpp
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexTGA.cpp
- Texconv/PortablePixMap.cpp
- build/OneFuzzConfig.json
- build/onefuzz-setup.ps1
In #413 I missed the bytes-per-pixel value in checking for 32-bit overflow for PPM image memory. I also had a typo so it was failing to actually return in this case too.
Also added explicit bounds checks for TGA and HDR readers. DDS reader already has bounds in place based on hardware limitations unless `DDS_FLAGS_ALLOW_LARGE_FILES` is used.
> Also fixed ASAN_OPTIONS problem.
> PPM TGA HDR bounds updates on readers

- DirectXTex/BC.h
- DirectXTex/BC6HBC7.cpp
- DirectXTex/BCDirectCompute.h
warning C5267 definition of implicit assignment operator for '{class}' is deprecated because it has a user-provided copy constructor
> Code review to silence some portability warnings

- CMakeLists.txt
- DirectXTex/DirectXTex.h
- Texassemble/AnimatedGif.cpp
- Texassemble/texassemble.cpp
- Texconv/ExtendedBMP.cpp
- Texconv/PortablePixMap.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
Also allows texassemble and texdiag to be built without requiring DX11 support.
> Fix warnings in tools for MinGW

- build/DirectXTex-OneFuzz.yml
In #438 the output directory of CMake was updated, so the OneFuzz pipeline need adjustment to match.
> OneFuzz ADO pipeline adjustments

- DirectXTex/DirectXTex_GDK_2019.vcxproj
- DirectXTex/DirectXTex_GDK_2022.vcxproj
- build/DirectXTex-GitHub-WSL-11.yml
- build/DirectXTex-GitHub-WSL.yml
- build/DirectXTex-OneFuzz.yml
* Added a target to the GDK projects to provide a more actionable error message in the case of the GDK not being installed -or- the VS integration is missing.
* Updated YAML because the `-o` parameter is ambiguous for modern PowerShell.
> Update GDK projects and ADO pipelines

- Texassemble/texassemble.cpp
Since #368 had been sitting around a while, the merge resulted in build breaks. This fixes those issues which were due to long-path support introduced in #364.
> Fix build breaks for texassemble

- DDSView/DDSView_Desktop_2019.vcxproj
- Texassemble/Texassemble_Desktop_2019.vcxproj
- Texassemble/Texassemble_Desktop_2019_Win10.vcxproj
- Texconv/Texconv_Desktop_2019.vcxproj
- Texconv/Texconv_Desktop_2019_Win10.vcxproj
- Texdiag/texdiag_Desktop_2019.vcxproj
- Texdiag/texdiag_Desktop_2019_Win10.vcxproj
The `/CETCOMPAT` linker flag is already enabled for EXEs build by VS 2022, but is also supported by VS 2019 (16.11) via `AdditionalOptions`.
> Enable /CETCOMPAT when building with VS 2019

- build/DirectXTex-GitHub-CMake-Dev17.yml
- build/DirectXTex-GitHub-CMake-Xbox.yml
- build/DirectXTex-GitHub-CMake.yml
- build/DirectXTex-GitHub-GDK.yml
- build/DirectXTex-GitHub-MinGW.yml
- build/DirectXTex-GitHub-Test.yml
- build/DirectXTex-GitHub-WSL-11.yml
- build/DirectXTex-GitHub-WSL.yml
- build/DirectXTex-GitHub.yml
- build/DirectXTex-OneFuzz-Coverage.yml
Also adds coverage of `Auxiliary` code to CMake-based pipelines for EXR, JPEG, and PNG extensions.
> Update ADO pipeline exclusion paths

- DDSView/ddsview.cpp
They were printing warnings in Clang.
> ifdef Visual Studio pragmas.

- DirectXTex/DirectXTexHDR.cpp
Fixed an issue when decoding the HDR text header if there is no ending `\n` present.
> Fix for HDR codec to avoid buffer overread for some malformed files

- DirectXTex/DirectXTexUtil.cpp
- DirectXTex/d3dx12.h
The new align templates were also broken due to missing macro.
> Minor static assert update for Windows SDK (26100)
> Fix D3DX12 warnings

- DirectXTex/DirectXTexUtil.cpp
When building for Scarlett or Xbox One, the symbol ``DXGI_FORMAT_A4B4G4R4_UNORM`` is not defined even when using Windows SDK (26100).
> Fix build break when building for Xbox using latest Windows SDK

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexDDS.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
Some DDS files have invalid mipcount values for the amount of data provided. While ``-permissive`` already handles cases where the mipcount value in the header is "too big" for the size of the texture, this new ``-ignoremips`` option allows files that are simply missing data by only reading the top-level mip.
Also added support to **texdiag** for ``-permissive`` and ``-ignoremips`` (it already supported `-badtails`).
> texconv: -ignoremips options for reading some invalid DDS files

- CMakePresets.json
- DirectXTex/DirectXTexDDS.cpp
The vast majority of "DX10" extended header DDS files are written by D3DX10/D3DX11 or DirectXTex, and properly set the ``DDS_HEADER_DXT10.arraySize`` field to 1 or greater. Some 3rd party writer is setting it to '0' instead for '1' (thinking since it wasn't an array, it doesn't need a value here), which was a common pattern for mipLevels set to 0 for legacy DX9 format DDS files as well.
> Some DDS DX10 writers set arraySize to 0 instead of 1

- .github/workflows/codeql.yml
- .github/workflows/main.yml
- .github/workflows/msbuild.yml
- .github/workflows/msvc.yml
- .github/workflows/test.yml
- CMakePresets.json
- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
- build/DirectXTex-GitHub-CMake-Dev17.yml
- build/DirectXTex-GitHub-CMake-Xbox.yml
- build/DirectXTex-GitHub-CMake.yml
- build/DirectXTex-GitHub-Dev17.yml
- build/DirectXTex-GitHub-GDK.yml
- build/DirectXTex-GitHub-MinGW.yml
- build/DirectXTex-GitHub-Test-Dev17.yml
- build/DirectXTex-GitHub-Test.yml
- build/DirectXTex-GitHub-WSL.yml
- build/DirectXTex-GitHub.yml
- build/DirectXTex-SDL.yml
While most pipelines are hosted on ADO, this adds GitHub build actions that are available to everyone who forks the repo. This also uses GitHub actions to validate PRs where possible rather than ADO for security reasons.
Also enables the GitHub Action based CodeQL and PREfast analysis.
Minor code review.
> Added GitHub Actions for build and security analysis

- Auxiliary/DirectXTexEXR.cpp
OpenEXR format can includes metadata indicating the image is cubemap which is six images in a single file.
> Add cubemap support for OpenEXR

- Auxiliary/DirectXTexEXR.cpp
Some additional code review for the submission in #483
> Additional code review for OpenEXR

- ScreenGrab/ScreenGrab11.h
- ScreenGrab/ScreenGrab12.h
- ScreenGrab/ScreenGrab9.h
Fixes some Code Analysis warnings as you can't use `_In_opt_` with `std::function<>`.
> Minor SAL fix

- Auxiliary/DirectXTexPNG.cpp
Fixes an incorrect stride value for R8 images being exported to PNG on the experimental libpng SaveToPNGFile implementation.
Also updated to make it clear interlaced images are not supported.
> Fix exporting R8 files as PNG using libpng

- Auxiliary/DirectXTexJPEG.cpp
- CMakePresets.json
- build/DirectXTex-GitHub-Test-Dev17.yml
- build/DirectXTex-GitHub-Test.yml
Includes minor fix to JPEG module to not set ALPHA MODE for returned formats that lack alpha. This matches a fix made to the PNG module in #503 .
> ADO test pipeline updates

- DirectXTex/DirectXTex_Desktop_2019.vcxproj
- DirectXTex/DirectXTex_Desktop_2019_Win10.vcxproj
- DirectXTex/DirectXTex_Desktop_2022.vcxproj
- DirectXTex/DirectXTex_Desktop_2022_Win10.vcxproj
- DirectXTex/DirectXTex_GDK_2019.vcxproj
- DirectXTex/DirectXTex_GDK_2022.vcxproj
- DirectXTex/DirectXTex_GXDK_PC_2019.vcxproj
- DirectXTex/DirectXTex_GXDK_PC_2022.vcxproj
- DirectXTex/DirectXTex_Windows10_2022.vcxproj
Since CompileShaders might need ``WindowsSDKVersion`` this update passes that through.
> Update BWOI support in VC projects

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexUtil.cpp
When writing some code, I realized a simple helper that returned 8 vs 16 bytes for the BC formats would be a useful addition.
> Add BytesPerBlock helper

- .github/dependabot.yml
- .github/workflows/bvt.yml
- .github/workflows/test.yml
- .github/workflows/vcpkg.yml
- .github/workflows/wsl.yml
- CMakeLists.txt
- build/DirectXTex-GitHub-CMake-Dev17.yml
- build/DirectXTex-GitHub-CMake.yml
- build/DirectXTex-GitHub-MinGW.yml
- build/DirectXTex-GitHub-Test-Dev17.yml
- build/DirectXTex-GitHub-Test.yml
- build/DirectXTex-GitHub-WSL-11.yml
- build/DirectXTex-GitHub-WSL.yml
- build/DirectXTex-OneFuzz-Coverage.yml
- build/DirectXTex-OneFuzz.yml
- build/DirectXTex-SDL.yml
This builds the test suite such that it only needs a few test data files which are included directly in the test repo. This avoids LFS bandwidth traffic for the full set of test data and provides an automated BVT.
This PR makes sure ``assert`` macros in the library built for fuzz-testing remain in place even in release builds.
> Includes ADO YAML code review to clean up use of PATs, and to convert all use of vcpkg in the pipelines to 'manifest mode'.
> Also sets the dependabot to not spam quite so often for GHA.
> Add GitHub Action for BVTs with subset of tests

- DDSTextureLoader/DDSTextureLoader11.cpp
- DDSTextureLoader/DDSTextureLoader12.cpp
- DDSTextureLoader/DDSTextureLoader9.cpp
- DirectXTex/DirectXTexD3D12.cpp
- ScreenGrab/ScreenGrab11.cpp
- ScreenGrab/ScreenGrab12.cpp
- ScreenGrab/ScreenGrab9.cpp
Also updates ScreenGrab and DDSTextureLoader for latest changes.
> Fix DX12 Capture transition state handling for MSAA

- README.md
- build/DirectXTex-GitHub-SDK-prerelease.yml
- build/DirectXTex-GitHub-SDK-release.yml
As of Windows SDK version 10.0.26100.1834, ARM64 for Win32 "classic" Desktop no longer builds with the VS 2019 toolset. VS 2022 is required.
> VS 2019 Win32 on ARM64 is no longer supported

- Auxiliary/DirectXTexXbox.h
- CMakeLists.txt
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTex.inl
- DirectXTex/DirectXTexDDS.cpp
- ScreenGrab/ScreenGrab12.cpp
When #538 was added to make the type of `FromMemory` operations use something other than `void*`, this turns out to result in code-breaks for clients using C++17's ``std::byte*``.
This PR adds compat inlines to avoid requiring the client code add casts.
> Minor tweak to CMake to avoid requiring all clients use directxmath and directx-headers packages externally.
> Also a minor /analyze fix to ScreenGrab12
> Support using C++17 std::byte for FromMemory functions

- DDSTextureLoader/DDSTextureLoader11.cpp
- DDSTextureLoader/DDSTextureLoader12.cpp
- DDSTextureLoader/DDSTextureLoader9.cpp
- DirectXTex/DirectXTexCompressGPU.cpp
- DirectXTex/DirectXTexUtil.cpp
- Texconv/PortablePixMap.cpp
If you gave it a ``nullptr`` for the filename, it would return a Win32 result of "ERROR_PATH_NOT_FOUND". Makes more sense to early-out as an ``E_INVALIDARG``.
> Includes a few more minor tweaks for where invalid args should be returned.
> Minor code review change for PPM/PFM code

- Texconv/PortablePixMap.cpp
- Texconv/texconv.cpp
- build/DirectXTex-OneFuzz.yml
I added support for the 'float16' variant of PFM some time back. ImageMagick uses a `.phm` extension for these files instead of `.pfm`.
> My PFM codec only supports reading "PHM" files, and not writing them so there's no need to add another 'CODEC'
> texconv: Portable Half Map uses .phm extension

- Auxiliary/DirectXTexEXR.cpp
* Fixes C4266 warning introduced with newer releases of OpenEXR
* Fixes `-Wsign-conversion` warning with clang/LLVM
> Fix CodeQL warnings in OpenEXR module

- .github/workflows/main.yml
- .github/workflows/uwp.yml
- .github/workflows/vcpkg.yml
- CMakeLists.txt
- CMakePresets.json
- build/CompilerAndLinker.cmake
Also adds MinGW64 and AArch64 (ARM64) Clang coverage to Git Hub Actions.
> Add GitHub Actions to validate UWP via CMake

- Texconv/texconv.cpp
* Adds ``--ignore-srgb`` switch which passes `TGA_FLAGS_IGNORE_SRGB` or `WIC_FLAGS_IGNORE_SRGB` to the loader as appropriate.
* Adds ``--wic-uncompressed`` switch which applies to TIFF and HEIF.
* `--wic-lossless` should not be applied to JPEG as it only has a quality setting. This switch now only applies JPEG XR.
* Add `--wic-quality` handling for HEIF codec output.
* Remove ``heic`` as an option for output as the extension can read both, but only supports writing ``hief``.
> texconv: add --ignore-srgb, --wic-uncompressed and revisit --wic-lossless

- DirectXTex/DirectXTexDDS.cpp
The ``--ignore-mips`` flag add in #484 is intended as a 'header hack' to treats the mipLevel as if it were 1 in DDS files. This is a workaround for some corrupt files. This doesn't work on cubemaps, arrays, or cubemap arrays because of how miplevels are laid out in those files.
This change just makes ``--ignore-mips`` only work on arraySize=1 textures since modifying the mipLevel count is not correct for array textures with mips. For array textures/cubemaps, the flag is ignored.
> You can remove mips in general by copying out the top-level mips to a new image. The `texconv` tool will do this with `-m 1`.
> --ignore-mips does not apply to array textures

- .github/workflows/wsl.yml
- DirectXTex/DirectXTexTGA.cpp
> GNUC 10 and 11 not included in Linux runner image anymore. Now has GNUC 12, 13, and 14.
> Improve error reporting for TGAs with invalid palettes

- .github/workflows/bvt.yml
- .github/workflows/test.yml
- .github/workflows/vcpkg.yml
- .github/workflows/wsl.yml
In restricted workflows, there's no access to the repository variable that gives the latest stable VCPKG commit id. This adds logic to use the head commit id from the VCPKG registry if the variable isn't set.
> Update VCPKG GHAs to use head commit id if variable isn't set

- Auxiliary/DirectXTexEXR.cpp
- Auxiliary/DirectXTexXboxDDS.cpp
- DDSTextureLoader/DDSTextureLoader11.cpp
- DDSTextureLoader/DDSTextureLoader12.cpp
- DDSTextureLoader/DDSTextureLoader9.cpp
- DirectXTex/BC.cpp
- DirectXTex/BC.h
- DirectXTex/BC6HBC7.cpp
- DirectXTex/BCDirectCompute.cpp
- DirectXTex/DirectXTexCompressGPU.cpp
- DirectXTex/DirectXTexConvert.cpp
- DirectXTex/DirectXTexD3D12.cpp
- DirectXTex/DirectXTexDDS.cpp
- DirectXTex/DirectXTexHDR.cpp
- DirectXTex/DirectXTexMipmaps.cpp
- DirectXTex/DirectXTexResize.cpp
- DirectXTex/DirectXTexTGA.cpp
- ScreenGrab/ScreenGrab12.cpp
- Texassemble/texassemble.cpp
- Texconv/texconv.cpp
- Texdiag/texdiag.cpp
- WICTextureLoader/WICTextureLoader11.cpp
- WICTextureLoader/WICTextureLoader12.cpp
Both ``const auto`` and ``auto const`` are equivalent in terms of the C++ compiler parser, but general coding guidelines suggest using ``const auto``. The primary reason for this PR is to be consistent since the codebase was using both.
> Code review for const auto vs auto const

- DirectXTex/DirectXTexDDS.cpp
The DX10 DDS header extension has a field ``arraySize``. For 2D Texture Arrays, this is the number of textures in the array. For cubemaps and cubemapArrays, however, it is supposed to be the number of cubes (i.e. 1 is a single cube with 6 array entries, 2 for two cubemaps with 12 array entries, etc.). This is how D3DX10/D3DX11 write these files. Some writers, however, fail to handle this special case and write the original array count. This PR allows the loading of these files when using the ``--permissive`` option.
Note that the *GetMetadata* functions will return the original values from the header. The *Load* functions will fix up the metadata value returned when this scenario is detected.
> Support loading another DX10 DDS variant with permissive

- build/DirectXTex-GitHub-CMake.yml
- build/DirectXTex-GitHub-Test.yml
- build/DirectXTex-GitHub.yml
Remove cases of building for ARM64 with VS 2019 due to changes to Windows SDK (26100).
> Update ADO coverage for clang v12

- CMakePresets.json
- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexUtil.cpp
Depth/Stencil formats are explicitly considered "planar" by Direct3D 12, but were not in Direct3D 11. This PR updates **IsPlanar** with a defaulted optional parameter to handle these two choices, defaulting to Direct3D 11 as before.
> IsPlanar option for D3D12 vs D3D11 depth

- DirectXTex/DirectXTex.h
- DirectXTex/DirectXTexP.h
- DirectXTex/DirectXTexUtil.cpp
Adds helper to compute the 'shape' of 1D, 2D, and 3D tiles based on the format to get 64KiB sized texture tiles. This uses the 'standard' tiles as defined for Direct3D 11.2 and Direct3D 12, but does not support any Xbox-specific or IHV-specific tiling features.
> Add ComputeTileShape utility

- CMakeLists.txt
In #593 I did a cleanup for CMake which was correct for most scenarios. It turns out that legacy Durango (i.e. Xbox One XDK circa 2015 - 2018) which I still support for some projects still needs that behavior to successfully build.
> CMake fix for legacy Durango

- .azuredevops/policies/approvercountpolicy.yml
- DirectXTex/DirectXTex.h
CoPilot suggested a change which I disagreed with, but when I researched it a bit I realized there was a different change that would be useful to prefer `__attribute__` to `__declspec` for GNUC.
> Also includes some AzureDev Ops polices from the production pipelines.
> Code review feedback for DLL declimport/export

- DirectXTex/DirectXTex_GDK_2019.vcxproj
- DirectXTex/DirectXTex_GDK_2019.vcxproj.filters
- DirectXTex/DirectXTex_GDK_2022.vcxproj
- DirectXTex/DirectXTex_GDK_2022.vcxproj.filters
Since the GDK Gaming.*.x64 platforms don't build with DirectX 11 code, the shaders are not currently used.
> Fixed -Wmissing-include-dirs warnings

- Auxiliary/DirectXTexEXR.cpp
- Auxiliary/DirectXTexXbox.h
For the C++17 ``std::byte`` support (#545) I had to provide a ``std::nullptr_t`` overload for the standard **EncodeDDSHeader** because the pointer can be null, but for Xbox it can't be.
> Also in #564 I had picked the wrong code branch to keep in the EXR module which used ``CreateFileW`` when I wanted to always use ``CreateFile2``.
> EncodeDDSHeader for Xbox can't take a nullptr

- .github/workflows/bvt.yml
- .github/workflows/main.yml
- .github/workflows/test.yml
- .github/workflows/vcpkg.yml
Switched all impacted pipelines to use *windows-2022*, but I still make use of v142 toolset for validation of the "VS 2019 (16.11)" compiler.
> GitHub Actions windows-2019 runner is being retired
