Texassemble/texassemble.cpp

DirectXTex will load all the frames of an animated gif as an array, but it just resizes them to the same size. This ignores all the metadata that is actually required to properly compose the frames.
This change adds a ``gif`` command to the ``texassemble`` tool so that it does the proper animated gif frame composition.

texassemble support for animated gif

---

Texassemble/texassemble.cpp

Texassemble's merge was originally created to match legacy DXTex.exe behavior for "Open Alpha onto surface". This just pulled the Blue channel from the second image and placed it the Alpha channel of the first image preserving RGB.
To make this more general, there's now an optional ``-swizzle`` parameter for texassemble merge.  Lower case letters in the mask indicate the channel to use from the first image. Upper-case characters in the mask indicate channel to use from the second image.
```
texassemble merge -swizzle rrrR
```
This results in the Red channel of the first image placed into Red, Green, and Blue of the output. The Red channel of the second image image would be in the Alpha of the output.
```
texassemble merge -swizzle ggbA
```
This results in the Green channel of the first …

texassemble updated with -swizzle option for merge

---

DirectXTex/DirectXTexD3D12.cpp
DirectXTex/DirectXTexWIC.cpp

Gets rid of an unused variable and redundant assignment.

Get rid of redundancies

---

DirectXTex/DirectXTexD3D12.cpp
DirectXTex/d3dx12.h
ScreenGrab/ScreenGrab12.cpp

For details on this change, see [this blog post](https://devblogs.microsoft.com/oldnewthing/20220113-00/?p=106152).
Related to https://github.com/microsoft/DirectX-Headers/issues/72

Update to support ABI for MinGW in DX Agility SDK v1.606.3

---

DDSView/ddsview.cpp

When viewing legacy DX9 DDS format content, you often need to force SRGB to get gamma-correct viewing. This adds ``-forcesrgb`` to the **DDSView** sample command-line interface.

DDSView updated with -forcesrgb switch

---

LICENSE
README.md
SECURITY.md
build/DirectXTex-GitHub-CMake-Dev17.yml
build/DirectXTex-GitHub-CMake.yml
build/DirectXTex-GitHub-Dev17.yml
build/DirectXTex-GitHub-MinGW.yml
build/DirectXTex-GitHub-Test-Dev17.yml
build/DirectXTex-GitHub-Test.yml
build/DirectXTex-GitHub-WSL-11.yml
build/DirectXTex-GitHub-WSL.yml
build/DirectXTex-GitHub.yml

Update for latest files for MIT license and the SECURITY statement.
> Also tweaked CI/PR build triggers.

Update for latest files from the Microsoft GitHub template

---

.nuget/directxtex_desktop_2019.nuspec
.nuget/directxtex_desktop_win10.nuspec
.nuget/directxtex_uwp.nuspec
HISTORY.md
README.md

* Updated D3DX12 internal copy with latest changes from DirectX-Headers GitHub
* CMake project updates and fixes for clang/LLVM v16 warnings
* texassemble/texconv/texdiag: Windows on ARM64 version

April 28, 2023

---

.nuget/directxtex_uwp.nuspec
CMakePresets.json
DirectXTex/DirectXTexP.h
DirectXTex/DirectXTex_Windows10_2019.vcxproj
DirectXTex/DirectXTex_Windows10_2022.vcxproj
DirectXTex_Windows10_2019.sln
DirectXTex_Windows10_2022.sln
build/DirectXTex-GitHub-CMake-Dev17.yml
build/DirectXTex-GitHub-CMake.yml
build/DirectXTex-GitHub-Dev17.yml
build/DirectXTex-GitHub-SDK-prerelease.yml
build/DirectXTex-GitHub-SDK-release.yml
build/DirectXTex-GitHub.yml
build/Directory.Build.props

Update xbox branch with PR #387 and #386

Update Xbox with ARM32 architecture deprecation

---

DirectXTex/DirectXTexDDS.cpp

Some DDS writers incorrectly use the value of *24* instead of *124* for the size of the ``DDS_HEADER``. Otherwise the file is valid. This PR updates the DDS reader to accept these files if the ``DDS_FLAGS_PERMISSIVE`` flag is used.
For "DX10" extended header scenarios, the header size must always be **124**.

Read legacy files with a DDS_HEADER size of 24

---

CMakeLists.txt
CMakePresets.json
build/CopyASan.targets
build/DirectXTex-OneFuzz.yml
build/OneFuzzConfig.json

Provides file-fuzzing coverage for DDS, HDR, and TGA file codecs.

Add OneFuzz build pipeline

---

DirectXTex/DirectXTexD3D12.cpp
ScreenGrab/ScreenGrab12.cpp
Texconv/PortablePixMap.cpp
build/DirectXTex-SDL.yml
build/OneFuzzConfig.json

Also includes some minor code review.

texconv: Fix PFM reader to avoid overread of buffer

---

DirectXTex/DirectXTexMipmaps.cpp
build/DirectXTex-GitHub-MinGW.yml
build/DirectXTex-GitHub-Test-Dev17.yml
build/DirectXTex-GitHub-Test.yml
build/DirectXTex-GitHub-WSL-11.yml
build/DirectXTex-GitHub-WSL.yml
build/DirectXTex-OneFuzz.yml
build/DirectXTex-SDL.yml

* Use CodeQL 3000
* Minimize disk space usage for the cmake pipeline with tests
* YAML code review
> Includes minor code review feedback

Update ADO build pipelines

---

Auxiliary/DirectXTexEXR.cpp
CMakeLists.txt

Fixes https://github.com/microsoft/DirectXTex/issues/426 .

Remove references to ZLIB and edit comment as appropriate.

---

Auxiliary/DirectXTexXboxDetile.cpp
Auxiliary/DirectXTexXboxTile.cpp
DirectXTex/DirectXTex.h
DirectXTex/DirectXTexUtil.cpp

* Make use of XG's ``CopyFromSubresource`` and ``CopyToSubresource`` methods
* Add CalculateSubresource helper to ``TexMetadata``

Xbox auxiliary optimization for tiling

---

Auxiliary/DirectXTexXboxDetile.cpp
Auxiliary/DirectXTexXboxTile.cpp
DirectXTex/DirectXTexUtil.cpp

Fixes warning in release build introduced with #459

Fixed unreferenced formal parameter warning

---

HISTORY.md
README.md

* Xbox Auxiliary tiling/detiling code optimization

March 6, 2024

---

CMakePresets.json
build/CompilerAndLinker.cmake
build/DirectXTex-GitHub-CMake-Dev17.yml
build/DirectXTex-GitHub-CMake-Xbox.yml
build/DirectXTex-GitHub-CMake.yml
build/DirectXTex-GitHub-GDK-Dev17.yml
build/DirectXTex-GitHub-GDK.yml
build/DirectXTex-GitHub-MinGW.yml
build/DirectXTex-GitHub-Test.yml
build/DirectXTex-GitHub-WSL.yml
build/DirectXTex-GitHub.yml
build/SetupBWOI.cmd
build/SetupBWOI.targets

Includes an ADO pipeline update to validate GDKX builds using CMake.

Fix build issues with XboxOne and clang

---

CMakeLists.txt
DDSTextureLoader/DDSTextureLoader11.cpp
DirectXTex/DirectXTexMipmaps.cpp
DirectXTex/DirectXTex_Windows10_2022.vcxproj
DirectXTex/d3dx12.h
README.md
WICTextureLoader/WICTextureLoader11.cpp
build/DirectXTex-GitHub-Dev17.yml
build/DirectXTex-GitHub-Test-Dev17.yml
build/DirectXTex-GitHub.yml
build/DirectXTex-SDL.yml

Adds use of ``/analyze`` to the SDL pipeline.
Updates D3DX12 to latest version.

ADO pipeline changes for OpenSSF Best Practices

---

CMakePresets.json
build/DirectXTex-GitHub-Test-Dev17.yml

Adds ARM64EC presets per the instructions on [Microsoft Learn](https://learn.microsoft.com/en-us/windows/arm/arm64ec-build).

CMake updated to build ARM64EC

---

build/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
build/DirectXTex-GitHub-CMake-Xbox.yml
build/DirectXTex-GitHub-GDK-Dev17.yml
build/DirectXTex-GitHub-GDK.yml
build/DirectXTex-GitHub-SDK-prerelease.yml
build/DirectXTex-GitHub-SDK-release.yml
build/Directory.Build.props
build/placeholder.xvd

Various minor code review updates for ADO build pipelines.

Build pipeline updates

---

build/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
build/DirectXTex-GitHub-CMake-Xbox.yml
build/DirectXTex-GitHub-GDK-Dev17.yml
build/DirectXTex-GitHub-GDK.yml
build/DirectXTex-GitHub-SDK-prerelease.yml
build/DirectXTex-GitHub-SDK-release.yml
build/Directory.Build.props
build/SetupBWOI.targets

Includes some cleanup for BWOI scenarios

ADO pipeline for SDK builds

---

build/DirectXTex-GitHub-WSL-13.yml
build/DirectXTex-GitHub-WSL.yml

Also add a YAML for building with newer Ubuntu.

Fix some warnings in WSL build due to case

---

Auxiliary/DirectXTexXboxDetile.cpp
Auxiliary/DirectXTexXboxTile.cpp
build/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
build/DirectXTex-GitHub-GDK-Dev17.yml
build/DirectXTex-GitHub-WSL-11.yml
build/DirectXTex-GitHub-WSL-13.yml

Improves code quality for the Xbox tiling/detiling auxiliary functions.

CodeQL recommendations

---

.azuredevops/pipelines/DirectXTex-GitHub-CMake-Dev17.yml
.azuredevops/pipelines/DirectXTex-GitHub-CMake-Xbox-Dev17.yml
.azuredevops/pipelines/DirectXTex-GitHub-CMake-Xbox.yml
.azuredevops/pipelines/DirectXTex-GitHub-CMake.yml
.azuredevops/pipelines/DirectXTex-GitHub-GDK-Dev17.yml
.azuredevops/pipelines/DirectXTex-GitHub-GDK.yml
.azuredevops/pipelines/DirectXTex-GitHub-MinGW.yml
.azuredevops/pipelines/DirectXTex-GitHub-SDK-prerelease.yml
.azuredevops/pipelines/DirectXTex-GitHub-SDK-release.yml
.azuredevops/pipelines/DirectXTex-GitHub-Test.yml
.azuredevops/pipelines/DirectXTex-GitHub-VCPKG.yml
.azuredevops/pipelines/DirectXTex-GitHub-WSL-11.yml
.azuredevops/pipelines/DirectXTex-GitHub-WSL-13.yml

Moved `ADOFeedGUID`, `ADOFeedURL`, `GDK_EDITION` and `VCPKG_TAG` to a shared variable group.

Update ADO YAML to use shared variables
